/*
Message file for ARACHNE WWW browser

Notes for translators:

1) Please translate only quoted messages (text between " .... ")
2) Please keep symbols like %s, %d, etc. They will be replaced by program.
3) Symbol \n means line break
4) For German message file, there is one big inconvenience: text mode messages
   must be displayed in DOS code page, while graphics mode messages in Windows
   code page. This is because of characters with "umlauts".

*/

//Messages with (almost) unlimited size (one line of text):

#define MSG_START  "\nArachne V%s%s startuje...\n%s\n"
#define MSG_END    "\nArachne V%s%s%s uspesne skoncila...\n%s\n\n"
#define MSG_MEM    "Arachne nema dostatek konvencni (dolni) DOSovske pameti"
#define MSG_BYTES  ": (chybi %lu bytu)\n"
#define MSG_XSWAP  "Zakazana operace s xSwapem"
#define MSG_XDEL   "nelze mazat z xSwapu"
#define MSG_DELAY1 "Dáte si kávu ?"
#define MSG_DELAY2 "Moment, prosím..."
#define MSG_BREAK  "Pro pøeru¹ení stisknìte <Ctrl+Pause>."
#define MSG_ESC    "Pro pøeru¹ení stisknìte <Esc>..."
#define MSG_ANYKEY " stisknete cokoliv "
#define MSG_ALLOC  "Chyba pri alokaci pameti - %s !\nSnazim se dealokovat xSwap..."
#define MSG_DNSERR "Nemohu nalázt poèítaè %s - prosím zkontrolujte va¹e nastavení !"
#define MSG_BADEXE "Chyba v EXE souboru."
#define MSG_TCPIP  "Inicializuji TCP/IP..."
#define MSG_FONT   "Aktualizuji informace o fontech..."
#define MSG_RETURN "Pro navrat na WWW napiste 'arachne -r'\n"
#define MSG_THIS   "> Toto je NEKOMERCNI (neregistrovana) verze Arachne,%s<\n"
#define MSG_HANGUP "Ukonèuji telefonické spojení..."
#define MSG_ERRIMG "Obrázek nelze nahrát..."
#define MSG_CONV   "Zpracovávám '%s' => %s. %s %s"
#define MSG_PLUGIN "Zpracovávám '%s'. %s"
#define MSG_ERROR  "Chyba!"
#define MSG_NOTMEM "Stránka je pøíli¹ dlouhá !"
#define MSG_ABORT  "Pøenos dat byl pøeru¹en !"
#define MSG_ASKDNS "Dotazuji se name serveru na %s ..."
#define MSG_ERRCON "Nemohu se pøipojit na %s - prosím zkontrolujte va¹e nastavení !"
#define MSG_CON    "Pøipojuji se na %s, port %d ..."
#define MSG_REQ    "Navázáno spojení s %s - ¾ádám stránku '%s' ..."
#define MSG_POST   "Odesílán data metodou POST..."
#define MSG_READ   "Pøeèteno %d bytù.\n"
#define MSG_HTTP   "HTTP hlavièka "
#define MSG_REDIR  "Pøesmìrování..."
#define MSG_CLOSE  "Ukonèuji spojení..."
#define MSG_CLOSED "Spojení ukonèeno."
#define MSG_DOWNLD "Pøená¹ím soubor ("
#define MSG_X_OF_Y "%s%d %% z %ld bytù ) ..."
#define MSG_BYTESR "%s%ld bytù pøeèteno) ..."
#define MSG_MISOBJ "%d objektù chybí, "
#define MSG_DISK   "Nahrávám dokument z disku"
#define MSG_ADJUST "Upravuji rámeèky, obrázky a tabulky"
#define MSG_DLPERC "Stahuji dokument (%d %% of %ld bytù) ..."
#define MSG_DLBYTE "Stahuji dokument (%ld bytù pøeèteno) ..."
#define MSG_REDRAW "Obnovuji obrazovku..."
#define MSG_RENDER "Generuji virtuální obrazovku..."
#define MSG_FORM   "Processing form..."
#define MSG_FRAMES "This is multiple document:"
#define MSG_DELAY0 "Meditating..."
#define MSG_VERIFY "Ovìøuji obrázky..."
#define MSG_CFGERR "Chyba pøi ètení %s - del¹í ne¾ %d øádkù neboµ    nedostatek pamìti\n"
#define MSG_KILL   "Ru¹ím diskovou cache..."
#define MSG_DEAD   "Cache je nyní zru¹ena."
#define MSG_URL "Zadejte URL stránky kterou chcete prohlí¾et aµ    stisknìte <Enter> ..."
#define MSG_TCPERR "CHYBA: %s\n"
#define MSG_TCPILL "Nedovolený TCP/IP status: %d\n"
#define MSG_NOIP   "Nedefinovaná IP adresa !"
#define MSG_CONFIG "Aktualizuji konfiguraèní soubor..."
#define MSG_WRITE  "Zapisuji soubor..."
#define MSG_COPY   "Kopíruji..."
#define MSG_HOTLST "Lokace pøidána do hotlistu."
#define MSG_ERRHOT "Nelze zapisovat do hotlistu !"
#define MSG_FNTERR "Chyba pri nahravani fontu: "
#define MSG_MEMLFT "(Zbyvajici volna pamet = %lu)\n"
#define MSG_F5ZOOM "\n\nV tomto modu muzete pouzit <F5> nebo <*> k zobrazeni pres celou obrazovku\n\nProsim%s..."
#define MSG_VERR1  "\nNelze inicializovat video mod !"
#define MSG_VERR2 "Jestlize vase SVGA karta neni v nizee uvedenem seznamu, zkuste nainstalovat VESA driver."
#define MSG_VERR3 "Jestlize pouzivate 256 kB VGA kartu, nainstalujte prosim \"Arachne Light\"."
#define MSG_GIF "Pùvodní paleta=%d, GIF paleta=%d, Barev celkem=%d."
#define MSG_LDPAL  "Nahrávám %d palet ..."
#define MSG_MIXPAL "Mixuji paletu z %d barev ..."
#define MSG_BMP "Pùvodní paleta=%d, BMP=Truecolor, Barev celkem=%d."
#define MSG_ASKING "Pøipojeno. Asking for ®ádám'%s'..."
#define MSG_WTRPL  "Pøipojeno. Èekám na odezvu..."
#define MSG_RDRPL  "Ètu odpovìâ... (%ld bytù pøeèteno)"
#define MSG_CONVI  "Zpracovávám %d vlo¾ené objekty. %s %s"
#define MSG_LOGIN  "Pøihla¹uji se..."
#define MSG_DETECT "Zji¹tìno %lu zpráv (%lu bytù v mailboxu)\n"
#define MSG_GET1   "Naèítám zprávu # %lu z %lu (%lu%s"
#define MSG_GET2   "Naèítám zprávu # %lu (%lu bytù) z %lu (%lu%s"
#define MSG_GET3   " bytù v mailboxu)\n"
#define MSG_DELE   "Ma¾u zprávu # %lu z %lu"
#define MSG_SKIP "Vynechávám zprávu # %lu, pøíli¹µ    velká-nedostatek místa na disku \n"
#define MSG_ERROPN "Soubor nelze otevøít!"
#define MSG_MEMSEL "\nTypy pamìti pro swapování:\n"
#define MSG_SMTP   "Pøipojuji k SMTP serveru..."
#define MSG_ICON1  "Pøedchozí prohlí¾ený dokument"
#define MSG_ICON2  "Následující prohlí¾ený dokument"
#define MSG_ICON3  "Domácí stránka"
#define MSG_ICON4  "Vytisknout stránku"
#define MSG_ICON5  "Pøidání do hotlistu"
#define MSG_ICON6  "Hotlist"
#define MSG_ICON7  "Ukonèení Arachne"
#define MSG_ICON8  "Vyhledávání v rámci stránky"
#define MSG_ICON9  "Nápovìda"
#define MSG_ICONH  "Historie"
#define MSG_ZOOM   "Pøekreslit obrazovku"
#define MSG_EXIT   "Ukonèení Arachne"
#define MSG_INFO2  "Dal¹í informace"
#define MSG_DIAL2  "Nastavení pøipojení"
#define MSG_SEND   "Odesílám zprávu, %ld bytù of %ld..."
#define MSG_UPLOAD "Uploaduji dokument, %ld bytù z %ld..."
#define MSG_SENT   "%d bytù odesláno, èekám na odezvu..."
#define MSG_MAILUP "SMTP upload"
#define MSG_MAILDL "POP3 download"
#define MSG_REMOVE "Vymazáno %s"
#define MSG_DIAL   "Chvíli strpení, vytáèím telefoní èíslo! %s"
#define MSG_USEMAP "Linking client side imagemaps..."
#define MSG_PRN    "Konvertuji na  obyèejný text..."
#define MSG_SRCH1  "Vyhledávám '%s'..."
#define MSG_SRCH2  "Nenalezeno !"
#define MSG_IMAGE  "%s obrázek %dx%d"
#define MSG_COLORS ", %d barvy"
#define MSG_LINECOL"Øádek:%04d Sloupec:%03d"
#define MSG_SRCH4  "Prohledat dokument:"
#define MSG_ENTER  "Zadejte hledaný øetìzec a stisknìte <Enter>"
#define MSG_PS     "Tisknu PostScriptovou stránku # %d z %d ..."

//Messages with unlimited, but same size (use spaces to indent):

#define MSG_SELVGA   "Vyberte video kartu : "
#define MSG_RESOL    "Zvolte rozliseni : "
#define MSG_MEMORY "\nZvolte druh pameti : "

//Messages with limited size:

//                 >------------<
#define MSG_UNREG  "Unregistered"

//                 >-------|----|-----<
#define MSG_INFMSG " device free  used"

//(aproximately)   >-------------<
#define MSG_SAVE   "Ulo¾it/upload"
#define MSG_OPEN   "Nahrát/otevøí"
#define MSG_PRINT  "Tisk/export"
#define MSG_SEARCH "Hledat"
#define MSG_EDIT   "Editace"
#define MSG_SOURCE "Zdrojový text"
#define MSG_INFO   "Informace"
#define MSG_IMAGES "Nahrát obrázky"
#define MSG_MAIL   "Vá¹ e-mail"
#define MSG_HOME   "Desktop"

//(aproximately)   >------<
#define MSG_TITLE  "Titul:"