#ifdef AGB
#include "agb_msg.h"
#else

#ifdef TELEMED
#include "telemed.h"
#else

/*
Message file for ARACHNE WWW browser

Notes for translators:

1) Please translate only quoted messages (text between " .... ")
2) Please keep symbols like %s, %d, etc. They will be replaced by program.
3) Symbol \n means line break
4) For German message file, there is one big inconvenience: text mode messages
   must be displayed in DOS code page, while graphics mode messages in Windows
   code page. This is because of characters with "umlauts".

*/

//Messages with (almost) unlimited size (one line of text):

#define MSG_START  "\nArachne V%s%s está carregando...\n%s\n"
#define MSG_END    "\nArachne V%s%s%s foi carregado com sucesso no DOS...\n%s\n\n"
#define MSG_ENDX   "Arachne foi carregado com sucesso...\n\n"
#define MSG_MEM    "Arachne esgotou a memoria convencional (baixa) do DOS"
#define MSG_MEMERR "Arachne esgotou a memoria - a alocação malloc() falhou.\n"
#define MSG_BYTES  ": (%lu bytes faltantes\n"
#define MSG_XSWAP  "Operaçã ilegal de xSwap"
#define MSG_XDEL   "Não é possível deletar do xSwap"
#define MSG_DELAY1 "Gostaria de um cafezinho ?"
#define MSG_DELAY2 "Um momento, por favor..."
#define MSG_BREAK  "<Ctrl+Pause> aborta."
#define MSG_ESC    "<Esc> aborta..."
#define MSG_ANYKEY " pressione qualquer tecla "
#define MSG_ALLOC  "Erro de alocação de memória - %s na linha %d do arquivo %s!\nTentando de-alocar xSwap..."
#define MSG_DNSERR "Não foi possível localizar o computador %s - por favor verifique a configuração !"
#define MSG_BADEXE "Erro no arquivo EXE."
#define MSG_TCPIP  "Initializando TCP/IP..."
#define MSG_FONT   "Atualizando informação de fonte..."
#define MSG_RETURN "Tecle 'arachne -r' para retornar a World Wide Web.\n"
#define MSG_THIS   "> Esta é uma versão NãO-COMERCIAL (não registrada) do Arachne,%s<\n"
#define MSG_HANGUP "Terminando conexão discada (dial-up)..."
#define MSG_ERRIMG "Não foi possível carregar a imagem..."
#define MSG_CONV   "Processando '%s' [%s]. %s %s"
#define MSG_PLUGIN "Processando '%s'. %s"
#define MSG_ERROR  "Erro!"
#define MSG_NOTMEM "Página é longa demais !"
#define MSG_ABORT  "Transferência interrompida !"
#define MSG_ASKDNS "Procurando servidor de nome para %s ..."
#define MSG_ERRCON "Não foi possível conectar no %s - por favor, verifique a configuração !"
#define MSG_CON    "Conectando no %s, porta %u ..."
#define MSG_REQ    "Conectado no %s - solicitando objeto '%s' ..."
#define MSG_POST   "Enviando dados..."
#define MSG_READ   "%d bytes foram lidos.\n"
#define MSG_HTTP   "Cabeçalho HTTP de"
#define MSG_REDIR  "Redirecionando..."
#define MSG_CLOSE  "Fechando a conexão..."
#define MSG_CLOSED "Conexão fechada."
#define MSG_DOWNLD "Transferindo o arquivo ("
#define MSG_X_OF_Y "%s%ld de %ld bytes ) ..."
#define MSG_BYTESR "%s%ld bytes lidos) ..."
#define MSG_MISOBJ "%d objeto faltante, "
#define MSG_DISK   "Carregando a página do disco"
#define MSG_ADJUST "Ajustando frames, imagens e tabelas"
#define MSG_DLPERC "Transferindo página (%ld de %ld bytes) ..."
#define MSG_DLBYTE "Transferindo página (%ld bytes lidos) ..."
#define MSG_REDRAW "Atualizando a tela..."
#define MSG_RENDER "Gerando a tela virtual..."
#define MSG_FORM   "Processando formulário..."
#define MSG_FRAMES "Isto é um documento múltiplo:"
#define MSG_DELAY0 "Meditando..."
#define MSG_VERIFY "Verificando imagens..."
#define MSG_CFGERR "Erro lendo %s:\nArquivo não encontrado, o arquivo é menor que %d linhas ou esgotou a memória\n"
#define MSG_KILL   "Apagando o cache de disco..."
#define MSG_DEAD   "O cache foi apagado."
#define MSG_URL    "Digite o URL que deseja surfar e tecle <Enter> ..."
#define MSG_TCPERR "ERRO: %s\n"
#define MSG_TCPILL "Status de TCP/IP ilegal: %d\n"
#define MSG_NOIP   "Endereço IP não definido !"
#define MSG_CONFIG "Atualizando o arquivo de configuração..."
#define MSG_WRITE  "Escrevendo arquivo..."
#define MSG_COPY   "Copiando..."
#define MSG_HOTLST "URL '%.40s' foi adicionado em Favoritos."
#define MSG_ERRHOT "Não foi possível escrever no Favoritos !"
#define MSG_FNTERR "Erro no carregamento do arquivo de fontes: "
#define MSG_MEMLFT "(memória livre disponível = %lu)\n"
#define MSG_F5ZOOM "\n\nNeste modo você pode usar as teclas <F5> ou <*> para mudar para o modo de tela-cheia.\n\nPor favor%s..."
#define MSG_VERR1  "\nNão foi possível inicializar o modo de vídeo - por favor, execute o setup.bat !"
#define MSG_APCK   "\nNão foi possível carregar o arachne.pck - por favor, execute o setup.bat !"
#define MSG_GIF    "Paleta de cores original=%d, paleta GIF=%d, Total de cores=%d."
#define MSG_LDPAL  "Carregando %d paletas de cores ..."
#define MSG_MIXPAL "Combinando paleta de %d cores ..."
#define MSG_BMP    "Paleta original=%d, BMP=Truecolor, Total de cores=%d."
#define MSG_ASKING "Conectado. Procurando por '%s'..."
#define MSG_WTRPL  "Conectado. Aguardando a resposta..."
#define MSG_RDRPL  "Lendo resposta... (%ld bytes lidos)"
#define MSG_CONVI  "Processando %d objetos incluidos. %s %s"
#define MSG_LOGIN  "Efetuando o Logon em..."
#define MSG_DETECT "Detetado %lu menssagens (%lu bytes na caixa de entrada)\n"
#define MSG_GET1   "Obtendo menssagem # %lu of %lu (%lu%s"
#define MSG_GET2   "Obtendo menssagem # %lu (%lu bytes) de %lu (%lu%s"
#define MSG_GET3   " bytes na caixa de entrada)\n"
#define MSG_DELE   "Deletando menssagem # %lu de %lu"
#define MSG_SKIP   "Pulando a menssagem # %lu, grande de mais para o espaço de disco disponível\n"
#define MSG_ERROPN "Não foi possível abrir o arquivo!"
#define MSG_SMTP   "Conectando ao servidor SMTP..."
#define MSG_ICON1  "Páginas visitadas anteriormente"
#define MSG_ICON2  "Páginas a visitar"
#define MSG_ICON3  "Homepage"
#define MSG_ICON4  "Recarregar"
#define MSG_ICON5  "Adicionar ao Favoritos"
#define MSG_ICON6  "Favoritos"
#define MSG_ICON7  "Abortar transferência"
#define MSG_ICON8  "Mecanismo de Busca"
#define MSG_ICON9  "Ajuda"
#define MSG_ICONH  "Histórico"
#define MSG_ZOOM   "Redimensionar"
#define MSG_EXIT   "Sair do Arachne"
#define MSG_INFO2  "Mais informações"
#define MSG_DIAL2  "Página de controle de conexão"
#define MSG_SEND   "Enviando mensagem, %ld bytes de %ld..."
#define MSG_UPLOAD "Transferindo arquivo, %ld bytes de %ld..."
#define MSG_SENT   "%d bytes enviados, aguardando pela resposta..."
#define MSG_MAILUP "Upload via SMTP"
#define MSG_MAILDL "Download do POP3"
#define MSG_REMOVE "Deletado %s"
#define MSG_DIAL   "Aguarde um momento, discando ! %s"
#define MSG_USEMAP "Criando ligação para mapa de imagens..."
#define MSG_PRN    "Convertendo para texto puro..."
#define MSG_SRCH1  "Procurando por '%s'..."
#define MSG_SRCH2  "Não encontrado !"
#define MSG_IMAGE  "%s imagem %dx%d"
#define MSG_COLORS ", %d cores"
#define MSG_LINECOL "Linha:%04d/%04d Coluna:%03d"
#define MSG_SRCH4  "Buscar"
#define MSG_ENTER  "Digite o texto a buscar e tecle <Enter>"
#define MSG_PS     "Imprimindo página PostScript # %d de %d ..."
#define MSG_CLPDEL "Você pode remover o objeto selecionado usando a tecla de <Delete> ..."
#define MSG_CLPADD "Você pode adicionar links selecionados a Favoritos..."
#define MSG_EDTADD "Título"
#define MSG_AENTER "Edite o nome e tecle <Enter>"
#define MSG_BACKGR "Transferência paralela de imagens ("
#define MSG_IDENT  "Ignorando a solicitacao de IDENT na porta 113..."
#define MSG_EFNAME "Digite o nome do arquivo e tecle <Enter>"
#define MSG_REFRSH "Arachne voará para '%.40s' em %d segundos. %s"
#define MSG_DOCDON "%s (tempo de carga=%ld:%02d)"
#define MSG_BLOCK  "^B início do bloco, ^K  fim do block, ^C copia o bloco, ^M move o bloco, ^Y recortar o bloco"
#define MSG_NOVIRT "Não existe tela virtual para exportar !"
#define MSG_NOVGA  "Modo gráfico não suportado !"
#define MSG_BLCUT  "Recortar o bloco para a área de transferência"
#define MSG_BLCLIP "Copiar o bloco para a área de transferência"
#define MSG_BLPAST "Colar o bloco da área de transferência"
#define MSG_MISLNK "Links perdidos: %d"
#define MSG_ERRIKN "Erro no processamento do arquivo de ícones. Não é possível mostrar a interface do usuário !\n"
#define MSG_BLCKWR "Bloco foi escrito."

#define MSG_MEMSEL "\nTipos de memória disponíveis para a troca:\n"
#define MSG_MEMXMS "0. XMS (recomendado) [Enter]"
#define MSG_MEMEMS "1. EMS (for XT/AT)"
#define MSG_MEMDSK "2. Disco (ultima opcao)"
#define MSG_MEMORY "\nSelecione o tipo de memória [Esc para abortar]: "

#define MSG_VGASEL "\nCategorias de placa de vídeo disponíveis:\n"
#define MSG_VGAVGA "0. VGA (recomendado) [Enter]"
#define MSG_VGAEGA "1. EGA (histórico)"
#define MSG_VGACGA "2. CGA (experimental)"
#define MSG_VIDEO  "\nSelecione o tipo de vídeo [Esc para abortar]: "

//Messages with limited size:

//                 >------------<
#define MSG_UNREG  "Sem Registro"

//                 >-------|----|-----<
#define MSG_INFMSG " equip. livr usado"

//(aproximately)   >-------------<
#define MSG_SAVE   "Salvar/upload"
#define MSG_OPEN   "Abrir URL"
#define MSG_PRINT  "Imp./Exportar"
#define MSG_SEARCH "Buscar na página"
#define MSG_EDIT   "Edição local"
#define MSG_SOURCE "Página de origem"
#define MSG_INFO   "Página de info"
#define MSG_IMAGES "Carregar imagens"
#define MSG_MAIL   "Seu eMail"
#define MSG_HOME   "Desktop"
#define MSG_WRITEF "Escrever arquivo"
#define MSG_READF  "Ler arquivo"
#define MSG_SRCHTX "Busca no texto"
#define MSG_PRT    "Imprimir"
#define MSG_BLKCUT "Recortar"
#define MSG_BLKCLP "Para área transf."
#define MSG_BLKPST "Colar"
#define MSG_BLKCOP "Copiar"
#define MSG_BLKMOV "Mover"
#define MSG_BLKDEL "Deletar"

//(aproximately)   >------<
#define MSG_TITLE  "Título"

#endif
#endif
